# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  update-theme:
    cmds:
      - git submodule update --remote --merge

  generate:
    cmds:
      - npx @tailwindcss/cli -i ./tailwind.css -o ./assets/css/extended/tailwind.css

  learning-plan:
    dir: /home/whlapinel/personal_projects/portfolio_hugo
    desc: copies marp slides from learning plan into static directory
    cmds:
      - rsync -av --delete --include='*/' --include='_index.md' --exclude='*' ../../mob_learning/ ./portfolio/content/projects/learning-plan
      - rsync -av --delete --include='*/' --include='*.html' --exclude='*' ../../mob_learning/ ./portfolio/static/learning-plan