// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const deleteCourse = `-- name: DeleteCourse :one
DELETE FROM courses WHERE id = ?
RETURNING id, name, description
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRowContext(ctx, deleteCourse, id)
	var i Course
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteCourseInstance = `-- name: DeleteCourseInstance :one
DELETE FROM course_instances WHERE id = ?
RETURNING id, course_id, term_id
`

func (q *Queries) DeleteCourseInstance(ctx context.Context, id int64) (CourseInstance, error) {
	row := q.db.QueryRowContext(ctx, deleteCourseInstance, id)
	var i CourseInstance
	err := row.Scan(&i.ID, &i.CourseID, &i.TermID)
	return i, err
}

const deleteDate = `-- name: DeleteDate :one
DELETE FROM dates WHERE course_instance_id = ? and lesson_id = ?
RETURNING course_instance_id, lesson_id, date
`

type DeleteDateParams struct {
	CourseInstanceID int64
	LessonID         int64
}

func (q *Queries) DeleteDate(ctx context.Context, arg DeleteDateParams) (Date, error) {
	row := q.db.QueryRowContext(ctx, deleteDate, arg.CourseInstanceID, arg.LessonID)
	var i Date
	err := row.Scan(&i.CourseInstanceID, &i.LessonID, &i.Date)
	return i, err
}

const deleteDayNumber = `-- name: DeleteDayNumber :one
DELETE FROM day_numbers WHERE id = ?
RETURNING id, lesson_id, day
`

func (q *Queries) DeleteDayNumber(ctx context.Context, id int64) (DayNumber, error) {
	row := q.db.QueryRowContext(ctx, deleteDayNumber, id)
	var i DayNumber
	err := row.Scan(&i.ID, &i.LessonID, &i.Day)
	return i, err
}

const deleteLesson = `-- name: DeleteLesson :one
DELETE FROM lessons WHERE id = ?
RETURNING id, unit_id, number, name, description
`

func (q *Queries) DeleteLesson(ctx context.Context, id int64) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, deleteLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Number,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const deleteNonInstructDays = `-- name: DeleteNonInstructDays :one
DELETE FROM non_instruct_days WHERE id = ?
RETURNING id, date
`

func (q *Queries) DeleteNonInstructDays(ctx context.Context, id interface{}) (NonInstructDay, error) {
	row := q.db.QueryRowContext(ctx, deleteNonInstructDays, id)
	var i NonInstructDay
	err := row.Scan(&i.ID, &i.Date)
	return i, err
}

const deleteTerm = `-- name: DeleteTerm :one
DELETE FROM terms WHERE id = ?
RETURNING id, start, "end"
`

func (q *Queries) DeleteTerm(ctx context.Context, id int64) (Term, error) {
	row := q.db.QueryRowContext(ctx, deleteTerm, id)
	var i Term
	err := row.Scan(&i.ID, &i.Start, &i.End)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :one
DELETE FROM units WHERE id = ?
RETURNING id, course_id, number, name, description
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, deleteUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Number,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT
    c.id as course_id,
    c.name as course_name,
    d.day AS day_number,
    u.number AS unit_number,
    u.name AS unit_name,
    l.number AS lesson_number,
    l.name AS lesson_name
FROM 
    day_numbers d
JOIN 
    lessons l ON d.lesson_id = l.id
JOIN 
    units u ON l.unit_id = u.id
JOIN 
    courses c ON u.course_id = c.id
ORDER BY 
    d.day
`

type GetCoursesRow struct {
	CourseID     int64
	CourseName   string
	DayNumber    int64
	UnitNumber   int64
	UnitName     string
	LessonNumber int64
	LessonName   sql.NullString
}

func (q *Queries) GetCourses(ctx context.Context) ([]GetCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesRow
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(
			&i.CourseID,
			&i.CourseName,
			&i.DayNumber,
			&i.UnitNumber,
			&i.UnitName,
			&i.LessonNumber,
			&i.LessonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCourse = `-- name: SaveCourse :one
INSERT INTO courses (
  name, description
) VALUES (
  ?, ?
)
RETURNING id, name, description
`

type SaveCourseParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) SaveCourse(ctx context.Context, arg SaveCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, saveCourse, arg.Name, arg.Description)
	var i Course
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const saveCourseInstance = `-- name: SaveCourseInstance :one
INSERT INTO course_instances (
  course_id, term_id
) VALUES (
  ?, ?
)
RETURNING id, course_id, term_id
`

type SaveCourseInstanceParams struct {
	CourseID int64
	TermID   int64
}

func (q *Queries) SaveCourseInstance(ctx context.Context, arg SaveCourseInstanceParams) (CourseInstance, error) {
	row := q.db.QueryRowContext(ctx, saveCourseInstance, arg.CourseID, arg.TermID)
	var i CourseInstance
	err := row.Scan(&i.ID, &i.CourseID, &i.TermID)
	return i, err
}

const saveDate = `-- name: SaveDate :one
INSERT INTO dates (
  course_instance_id, lesson_id, date
) VALUES (
  ?, ?, ?
)
RETURNING course_instance_id, lesson_id, date
`

type SaveDateParams struct {
	CourseInstanceID int64
	LessonID         int64
	Date             string
}

func (q *Queries) SaveDate(ctx context.Context, arg SaveDateParams) (Date, error) {
	row := q.db.QueryRowContext(ctx, saveDate, arg.CourseInstanceID, arg.LessonID, arg.Date)
	var i Date
	err := row.Scan(&i.CourseInstanceID, &i.LessonID, &i.Date)
	return i, err
}

const saveDayNumber = `-- name: SaveDayNumber :one
INSERT INTO day_numbers (
  lesson_id, day
) VALUES (
  ?, ?
)
RETURNING id, lesson_id, day
`

type SaveDayNumberParams struct {
	LessonID int64
	Day      int64
}

func (q *Queries) SaveDayNumber(ctx context.Context, arg SaveDayNumberParams) (DayNumber, error) {
	row := q.db.QueryRowContext(ctx, saveDayNumber, arg.LessonID, arg.Day)
	var i DayNumber
	err := row.Scan(&i.ID, &i.LessonID, &i.Day)
	return i, err
}

const saveLesson = `-- name: SaveLesson :one
INSERT INTO lessons (
  number, name, description, unit_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, unit_id, number, name, description
`

type SaveLessonParams struct {
	Number      int64
	Name        sql.NullString
	Description sql.NullString
	UnitID      int64
}

func (q *Queries) SaveLesson(ctx context.Context, arg SaveLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, saveLesson,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.UnitID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Number,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const saveTerm = `-- name: SaveTerm :one
INSERT INTO terms (
  start, end
) VALUES (
  ?, ?
)
RETURNING id, start, "end"
`

type SaveTermParams struct {
	Start string
	End   string
}

func (q *Queries) SaveTerm(ctx context.Context, arg SaveTermParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, saveTerm, arg.Start, arg.End)
	var i Term
	err := row.Scan(&i.ID, &i.Start, &i.End)
	return i, err
}

const saveUnit = `-- name: SaveUnit :one
INSERT INTO units (
  number, name, description, course_id 
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, course_id, number, name, description
`

type SaveUnitParams struct {
	Number      int64
	Name        string
	Description sql.NullString
	CourseID    int64
}

func (q *Queries) SaveUnit(ctx context.Context, arg SaveUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, saveUnit,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.CourseID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Number,
		&i.Name,
		&i.Description,
	)
	return i, err
}
