// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Course struct {
	ID          int64
	TemplateID  sql.NullInt64
	TermID      sql.NullInt64
	Name        string
	Description sql.NullString
}

type Date struct {
	ID        int64
	TermID    int64
	DayNumber int64
	Date      string
}

type Lesson struct {
	ID          int64
	UnitID      int64
	TemplateID  sql.NullInt64
	Number      int64
	Name        sql.NullString
	Description sql.NullString
}

type LessonDate struct {
	LessonID int64
	DateID   int64
}

type LessonObjective struct {
	ID       int64
	ObjID    int64
	LessonID int64
}

type NonInstructDay struct {
	ID     int64
	TermID int64
	Date   string
}

type Objective struct {
	ID     int64
	StdID  int64
	Number int64
	Name   string
}

type Standard struct {
	ID       int64
	CourseID int64
	Number   int64
	Name     string
}

type Term struct {
	ID    int64
	Name  string
	Start string
	End   string
}

type Unit struct {
	ID          int64
	CourseID    int64
	TemplateID  sql.NullInt64
	Number      int64
	Name        string
	Description sql.NullString
}

type UnitStandard struct {
	ID         int64
	CourseID   int64
	StandardID int64
}
